export const ListOfEmployee = [
	{
		id: 111,
		name: 'John',
		age: 21,
		email_address: 'john@example.com',
		password: 'password',
		phone: '1232356566',
		role: 'cashier',
		base_salary: 1.2,
	},
	{
		id: 111,
		name: 'John',
		age: 21,
		email_address: 'john@example.com',
		password: 'password',
		phone: '1232356566',
		role: 'cashier',
		base_salary: 1.2,
	},
	{
		id: 111,
		name: 'John',
		age: 21,
		email_address: 'john@example.com',
		password: 'password',
		phone: '1232356566',
		role: 'cashier',
		base_salary: 1.2,
	},
	{
		id: 111,
		name: 'John',
		age: 21,
		email_address: 'john@example.com',
		password: 'password',
		phone: '1232356566',
		role: 'cashier',
		base_salary: 1.2,
	},
	{
		id: 111,
		name: 'John',
		age: 21,
		email_address: 'john@example.com',
		password: 'password',
		phone: '1232356566',
		role: 'cashier',
		base_salary: 1.2,
	},
	{
		id: 111,
		name: 'John',
		age: 21,
		email_address: 'john@example.com',
		password: 'password',
		phone: '1232356566',
		role: 'cashier',
		base_salary: 1.2,
	},
	{
		id: 111,
		name: 'John',
		age: 21,
		email_address: 'john@example.com',
		password: 'password',
		phone: '1232356566',
		role: 'cashier',
		base_salary: 1.2,
	},
	{
		id: 111,
		name: 'John',
		age: 21,
		email_address: 'john@example.com',
		password: 'password',
		phone: '1232356566',
		role: 'cashier',
		base_salary: 1.2,
	},
	{
		id: 111,
		name: 'John',
		age: 21,
		email_address: 'john@example.com',
		password: 'password',
		phone: '1232356566',
		role: 'cashier',
		base_salary: 1.2,
	},
];
