export const ADD_TASK_GUARD = 'ADD_TASK_GUARD';
export const ADD_TASK_CASHIER = 'ADD_TASK_CASHIER';
// WORK-SHEET
export const RECORD_CHANGE = 'RECORD_CHANGE';
export const FETCH_LIST_TO_SELECT = 'FETCH_LIST_TO_SELECT';
export const FETCH_CALENDER_DAY = 'FETCH_CALENDER_DAY';
export const FETCH_LIST_NAME_BY_ROLE = 'FETCH_LIST_NAME_BY_ROLE';
export const FETCH_CREATE_NEW_WORKSHEET = 'FETCH_CREATE_NEW_WORKSHEET';
export const FETCH_ALL_WORKSHEET_BY_DATE = 'FETCH_ALL_WORKSHEET_BY_DATE';
export const FETCH_WORKSHEET_BY_ID = 'FEATCH_WORKSHEET_BY_ID';
