export const INIT_LEAVE_LIST = 'INIT_LEAVE_LIST';
export const ACT_FETCH_LEAVE_DETAILS = 'ACT_FETCH_LEAVE_DETAILS';
export const ACT_APPROVED_FORM = 'ACT_APPROVED_FORM';
export const ACT_REJECTED_FORM = 'ACT_REJECTED_FORM';
